### PR TITLE
Setting the master code base equal to Dev code base.

### PR DESCRIPTION
**Pull request by landoshepherd**
At this point, the master and the dev branches should match. This is a pull request to match the branches.

### CODE REVIEW

**Comment by DaricusDuncan** [comment]
Did you validate all your unit test and validations before merging into 'master'? Also, why was there a need to revert?..curious

**Comment by landoshepherd** [comment]
I screwed something up. I think I misunderstood why it said that the master branch was behind. When I merged working dev branch to master branch, it was still behind. Then I tried to revert to get it back to where I was so that I can try again. I ended up messing up a few things. When I get home today I am going to take a look at what went wrong and how to correct it.

**Comment by landoshepherd** [comment]
Also, I don’t any any unit test. I need to write them but I’m not sure how. Again, something I will look into tonight.

**Comment by DaricusDuncan** [comment]
Alright, sounds good. I will try to help with those unit tests towards the weekend.

**Pull request merged**
